//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class einnahme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public einnahme()
        {
            this.forderungs = new HashSet<forderung>();
        }
    
        public int einnahmeID { get; set; }
        public Nullable<int> kategorie { get; set; }
        public string bezeichnung { get; set; }
        public decimal betrag { get; set; }
        public System.DateTime eingang { get; set; }
    
        public virtual zahlungskategorie zahlungskategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forderung> forderungs { get; set; }
    }
}
