//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class erstattung
    {
        public int erstattungsID { get; set; }
        public Nullable<int> zuMietvertrag { get; set; }
        public Nullable<int> anPerson { get; set; }
        public decimal betrag { get; set; }
        public string grund { get; set; }
        public Nullable<System.DateTime> fälligkeit { get; set; }
        public Nullable<bool> erstattet { get; set; }
        public Nullable<System.DateTime> zahlungsdatum { get; set; }
    
        public virtual kontakt kontakt { get; set; }
        public virtual mietvertrag mietvertrag { get; set; }
    }
}
