//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class immoEntities : DbContext
    {
        public immoEntities()
            : base("name=immoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anrede> anredes { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<bankverbindung> bankverbindungs { get; set; }
        public virtual DbSet<dokument> dokuments { get; set; }
        public virtual DbSet<dokumentenkategorie> dokumentenkategories { get; set; }
        public virtual DbSet<einnahme> einnahmes { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<eMailNummernKat> eMailNummernKats { get; set; }
        public virtual DbSet<erstattung> erstattungs { get; set; }
        public virtual DbSet<forderung> forderungs { get; set; }
        public virtual DbSet<kategorie> kategories { get; set; }
        public virtual DbSet<kontakt> kontakts { get; set; }
        public virtual DbSet<leerstand> leerstands { get; set; }
        public virtual DbSet<miete> mietes { get; set; }
        public virtual DbSet<mieteinheit> mieteinheits { get; set; }
        public virtual DbSet<mietvertrag> mietvertrags { get; set; }
        public virtual DbSet<notiz> notizs { get; set; }
        public virtual DbSet<nummern> nummerns { get; set; }
        public virtual DbSet<objekt> objekts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<wohneinheitMiete> wohneinheitMietes { get; set; }
        public virtual DbSet<zahlungskategorie> zahlungskategories { get; set; }
        public virtual DbSet<vwEinheitDokumente> vwEinheitDokumentes { get; set; }
        public virtual DbSet<vwEinheitNotiz> vwEinheitNotizs { get; set; }
        public virtual DbSet<vwEinnahman> vwEinnahmen { get; set; }
        public virtual DbSet<vwKontakte> vwKontaktes { get; set; }
        public virtual DbSet<vwMieteinheiten> vwMieteinheitens { get; set; }
        public virtual DbSet<vwObjektDokumente> vwObjektDokumentes { get; set; }
        public virtual DbSet<vwObjekte> vwObjektes { get; set; }
        public virtual DbSet<vwObjektNotiz> vwObjektNotizs { get; set; }
        public virtual DbSet<vwPersonBankverbindung> vwPersonBankverbindungs { get; set; }
        public virtual DbSet<vwPersonenErstattungen> vwPersonenErstattungens { get; set; }
        public virtual DbSet<vwPersonenForderungen> vwPersonenForderungens { get; set; }
        public virtual DbSet<vwVertragDokumente> vwVertragDokumentes { get; set; }
        public virtual DbSet<vwVerträge> vwVerträge { get; set; }
        public virtual DbSet<vwVerträgeUndLeerstände> vwVerträgeUndLeerstände { get; set; }
        public virtual DbSet<vwVertragNotiz> vwVertragNotizs { get; set; }
        public virtual DbSet<vwVertragsforderung> vwVertragsforderungs { get; set; }
        public virtual DbSet<vwDokumente> vwDokumentes { get; set; }
        public virtual DbSet<vwKontaktDokumente> vwKontaktDokumentes { get; set; }
        public virtual DbSet<vwKontaktNotiz> vwKontaktNotizs { get; set; }
        public virtual DbSet<vwObjektEinheiten> vwObjektEinheitens { get; set; }
    }
}
