//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontakt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kontakt()
        {
            this.bankverbindungs = new HashSet<bankverbindung>();
            this.dokuments = new HashSet<dokument>();
            this.emails = new HashSet<email>();
            this.erstattungs = new HashSet<erstattung>();
            this.objekts = new HashSet<objekt>();
            this.notizs = new HashSet<notiz>();
            this.nummerns = new HashSet<nummern>();
            this.mietvertrags = new HashSet<mietvertrag>();
        }
    
        public int id { get; set; }
        public string kategorie { get; set; }
        public string anrede { get; set; }
        public string titel { get; set; }
        public string name { get; set; }
        public string vorname { get; set; }
        public string straße { get; set; }
        public string hausnr { get; set; }
        public string plz { get; set; }
        public string ort { get; set; }
        public Nullable<System.DateTime> gebDatum { get; set; }
        public string firma { get; set; }
    
        public virtual anrede anrede1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bankverbindung> bankverbindungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument> dokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email> emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erstattung> erstattungs { get; set; }
        public virtual kategorie kategorie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objekt> objekts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notiz> notizs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nummern> nummerns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mietvertrag> mietvertrags { get; set; }
    }
}
