//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mietvertrag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mietvertrag()
        {
            this.dokuments = new HashSet<dokument>();
            this.erstattungs = new HashSet<erstattung>();
            this.notizs = new HashSet<notiz>();
            this.forderungs = new HashSet<forderung>();
        }
    
        public int vertragsnr { get; set; }
        public int zuEinheit { get; set; }
        public int mieter { get; set; }
        public Nullable<System.DateTime> vertragsdatum { get; set; }
        public System.DateTime vertragsbeginn { get; set; }
        public Nullable<System.DateTime> vertragsende { get; set; }
        public Nullable<decimal> kaution { get; set; }
        public Nullable<int> kautionsraten { get; set; }
        public Nullable<bool> kautionBezahlt { get; set; }
        public string kündigungsfrist { get; set; }
        public Nullable<bool> mietverhältnisAktiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument> dokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erstattung> erstattungs { get; set; }
        public virtual kontakt kontakt { get; set; }
        public virtual mieteinheit mieteinheit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notiz> notizs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forderung> forderungs { get; set; }
    }
}
