//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mieteinheit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mieteinheit()
        {
            this.dokuments = new HashSet<dokument>();
            this.leerstands = new HashSet<leerstand>();
            this.wohneinheitMietes = new HashSet<wohneinheitMiete>();
            this.notizs = new HashSet<notiz>();
            this.mietvertrags = new HashSet<mietvertrag>();
        }
    
        public int mieteinheitID { get; set; }
        public int inObjekt { get; set; }
        public string bezeichnung { get; set; }
        public string etage { get; set; }
        public string lage { get; set; }
        public Nullable<decimal> fläche { get; set; }
        public Nullable<decimal> heizfläche { get; set; }
        public string stromzählernummer { get; set; }
        public Nullable<int> AnzWohnräume { get; set; }
        public Nullable<int> AnzBäder { get; set; }
        public Nullable<int> AnzKüchen { get; set; }
        public Nullable<int> AnzKeller { get; set; }
        public Nullable<int> AnzAbstellräume { get; set; }
        public Nullable<int> AnzBalkone { get; set; }
        public Nullable<int> AnzTerrassen { get; set; }
        public Nullable<int> AnzGaragen { get; set; }
        public Nullable<int> AnzStellplätze { get; set; }
        public Nullable<bool> Garten { get; set; }
        public Nullable<decimal> Gartenfläche { get; set; }
        public string weitereAusstattung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument> dokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leerstand> leerstands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wohneinheitMiete> wohneinheitMietes { get; set; }
        public virtual objekt objekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notiz> notizs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mietvertrag> mietvertrags { get; set; }
    }
}
