//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class miete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public miete()
        {
            this.wohneinheitMietes = new HashSet<wohneinheitMiete>();
        }
    
        public int mietID { get; set; }
        public decimal kaltmiete { get; set; }
        public System.DateTime gültigAb { get; set; }
        public decimal NkAbschlag { get; set; }
        public Nullable<decimal> garage { get; set; }
        public Nullable<decimal> stellplatz { get; set; }
        public Nullable<decimal> sonstMietbestandteile { get; set; }
        public bool aktiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wohneinheitMiete> wohneinheitMietes { get; set; }
    }
}
