//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEinnahman
    {
        public int Nr { get; set; }
        public string Kategorie { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Einnahmebetrag { get; set; }
        public System.DateTime Eingangsdatum { get; set; }
    }
}
