//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwForderungen
    {
        public int Forderungsnr { get; set; }
        public string Kategorie { get; set; }
        public Nullable<System.DateTime> Fälligkeit { get; set; }
        public Nullable<int> Vertragsnr { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Mieteinheit { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public Nullable<bool> Erledigt { get; set; }
    }
}
