//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKontakte
    {
        public int KontaktID { get; set; }
        public string Kategorie { get; set; }
        public string Anrede { get; set; }
        public string Titel { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string Straße { get; set; }
        public string Nr { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Firma { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public string Kreditinstitut { get; set; }
    }
}
