//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKontaktDokumente
    {
        public Nullable<System.DateTime> datum { get; set; }
        public string Art { get; set; }
        public string titel { get; set; }
        public string zu_Person { get; set; }
        public int id { get; set; }
    }
}
