//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKontaktNotiz
    {
        public Nullable<System.DateTime> datum { get; set; }
        public string Notiz { get; set; }
        public string Person { get; set; }
        public string firma { get; set; }
        public int id { get; set; }
    }
}
