//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMieteinheiten
    {
        public int NR { get; set; }
        public string Bezeichnung { get; set; }
        public string Lage { get; set; }
        public int ObjektNr { get; set; }
        public string Objekt { get; set; }
        public Nullable<int> Vertragsnr { get; set; }
        public string Mieter { get; set; }
        public Nullable<decimal> Nettomiete { get; set; }
        public Nullable<decimal> NK_Abschlag { get; set; }
        public Nullable<decimal> sonst__Mietanteile { get; set; }
        public Nullable<decimal> Bruttomiete { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    }
}
