//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwObjektEinheiten
    {
        public string Objekt { get; set; }
        public string Mieteinheit { get; set; }
        public string Lage { get; set; }
        public string akt__Mieter { get; set; }
        public Nullable<decimal> Bruttomiete { get; set; }
        public int objektID { get; set; }
    }
}
