//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwObjekte
    {
        public int Objektnummer { get; set; }
        public string Bezeichnung { get; set; }
        public string Straße { get; set; }
        public string Nr { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Vermieter { get; set; }
        public string Stromzähler { get; set; }
        public string Wasserzähler { get; set; }
        public string Gaszähler { get; set; }
        public Nullable<int> Baujahr { get; set; }
    }
}
