//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPersonenErstattungen
    {
        public int KontaktID { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public int ErstattungsNr { get; set; }
        public string Erstattungsgrund { get; set; }
        public Nullable<System.DateTime> Fällig_am { get; set; }
        public decimal Betrag { get; set; }
        public Nullable<System.DateTime> Erstattet_am { get; set; }
        public Nullable<bool> erledigt { get; set; }
    }
}
