//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPersonBankverbindung
    {
        public int KontaktID { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public string Kreditinstitut { get; set; }
        public string Straße { get; set; }
        public string nr { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Land { get; set; }
        public string Ansprechpartner { get; set; }
    }
}
