//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVerträge
    {
        public int Vertragsnr { get; set; }
        public string Objekt { get; set; }
        public string Mieteinheit { get; set; }
        public string Mieter { get; set; }
        public string Vermieter { get; set; }
        public System.DateTime Beginn { get; set; }
        public Nullable<System.DateTime> Ende { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    }
}
