//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVerträgeUndLeerstände
    {
        public int MiteinheitNr { get; set; }
        public Nullable<System.DateTime> Beginn_Leerstand { get; set; }
        public Nullable<System.DateTime> Ende_Leerstand { get; set; }
        public Nullable<System.DateTime> Vertragsbeginn { get; set; }
        public Nullable<System.DateTime> Vertragsende { get; set; }
        public string Mieter { get; set; }
    }
}
